### PR TITLE
Cleanup for Python3

### PR DESCRIPTION
**Pull request by darkdragon-001**
Using [`2to3` tool](https://docs.python.org/3/library/2to3.html), [`flynt` tool](https://github.com/ikamensh/flynt) and [`pyupgrade` tool](https://github.com/asottile/pyupgrade) together with manual fixes.

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
This looks good, how can we test it @darkdragon-001 ?

**Comment by darkdragon-001** [comment]
@ulfgebhardt I am trying to run all these scripts manually once. I will remove the `WIP:` prefix once all of them are working.

---

You should get a working setup for review as well:
```bash
$ git clone git@github.com:bundestag/gesetze-tools.git
$ cd gesetze-tools
$ python3 -m pip install -r requirements.txt
$ python3 <myscript.py> --help
```

All the scripts have will print a help page with usage examples.

**Comment by ulfgebhardt** [comment]
I will not do that locally, but on workflows thats cool.

I have put this together in 5mins https://github.com/bundestag/gesetze-tools/pull/19 - can you take a look and maybe get it to run? Feel free to merge it into this branch and fix it there so you can setup the right python versions etc.

**Comment by darkdragon-001** [comment]
> I will not do that locally, but on workflows thats cool.

Why not? You can also run this in a docker container
```
docker run -it --rm --entrypoint bash python:3.6
```

> I have put this together in 5mins #19 - can you take a look and maybe get it to run? Feel free to merge it into this branch and fix it there so you can setup the right python versions etc.

I will check it out the next days and comment in that PR.

> I will remove the WIP: prefix once all of them are working.

Syntax should be fine. Scraper functionality will be restored in separate commits. Can be merged.

**Review by ulfgebhardt — APPROVED** [review]

**Comment by ulfgebhardt** [comment]
Feel free to merge

**Pull request merged**
