### PR TITLE
Restore banz scraper and lawgit functionality

### PR DESCRIPTION
**Pull request by JBBgameich**

### CODE REVIEW

**Comment by JBBgameich** [comment]
Bisher funktioniert von den scrapern nur der banz_scraper (wir bekommen also nur Daten vom Bundesanzeiger). Mir fehlt noch das Hintergrundwissen ob wir damit Gesetzesänderungen verpassen, oder ob auch alles im BAnz veröffentlicht wird

**Comment by darkdragon-001** [comment]
We should coordinate our efforts. I have Python3 functionality restored in #17 and am working on the BGBl scraper in #19.

**Comment by JBBgameich** [comment]
This pull request is mostly about the banz scraper, I can probably get the first commit rebased on top of your automated porting work.

**Comment by ulfgebhardt** [comment]
https://discord.gg/YcQSvKcKB2

**Comment by JBBgameich** [comment]
Can we maybe just open issues for things we are working on? I'd like to avoid having to read yet another chat service.

**Comment by ulfgebhardt** [comment]
I am totally fine with issues - this is just for convenience, voice & video chat if needed for coordination

**Comment by JBBgameich** [comment]
This should be ready now. At least if you are okay with the added log function in lawgit, which I found useful to debug whether something is happening while it prints the same message multiple times so the console would not visibly change.

**Comment by JBBgameich** [comment]
GitHub seems to be a bit stupid again, on the branch the checks ran just fine, but they are not displayed here: https://github.com/JBBgameich/gesetze-tools/commits/restore-functionality. Is there anything I can do about it?

**Comment by ulfgebhardt** [comment]
You need to rebase

**Comment by ulfgebhardt** [comment]
your branch > rebase from master > force push > your branch > profit

**Comment by JBBgameich** [comment]
I already did that, as mentioned, the checks run fine on the branch

**Comment by ulfgebhardt** [comment]
Maybe thats a security feature to not expose potential secrets. I recommend to work directly on this Repo instead of a fork. I never had this problem before tho...

**Comment by JBBgameich** [comment]
It's a GitHub bug, the new pull request works.

**Comment by ulfgebhardt** [comment]
I think its about security. If you change the workflow and write a script which would expose a secret to the log it would be bad. But yeahr - makes forks even less usable as they are already - so considering it a bug might be valid ;)

**Comment by JBBgameich** [comment]
I doubt this is a security feature. The workflow ran just fine. The result was just not propagated to the pull request.

**Pull request closed without merging**
