### PR TITLE
Improve issue templates.

### PR DESCRIPTION
**Pull request by darkdragon-001**
## 🍰 Pullrequest
I modified the copied templates to be more suitable for this repository.

### Issues
- relates #34

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
I do not understand why you intentionally break the markdown syntax?! 👀

**Comment by darkdragon-001** [comment]
> I do not understand why you intentionally break the markdown syntax?! 👀

Can you give me an example? My markdown highlighting doesn't show me any problems... 

> Also why do you remove the comments and make it visible text? That makes no sense to me either

Such that people are forced to replace these instructions instead of ignoring them. Furthermore, especially for the question issue for people not familiar with Markdown, they might add their actual text inside the comment and could be wondering why their text isn't shown in the output. Plus, it's shorter.

**Comment by ulfgebhardt** [comment]
I mean you use the **bold** feature instead of headings. That's what I mean with breaking the syntax.
I will approve this - if you think its worthwhile.

**Review by ulfgebhardt — APPROVED** [review]

**Comment by darkdragon-001** [comment]
> I mean you use the **bold** feature instead of headings. That's what I mean with breaking the syntax.

I inspected some other repos and the majority seems to prefer _bold_ over _headline_. If you prefer headlines, I can use them as well. It's just that I don't like to use headlines for formatting when one doesn't use the whole hierarchy (e.g. no top-level headlines `#` since they appear too big for issues).

If you prefer headlines, tell me and I will convert it.

**Comment by ulfgebhardt** [comment]
Don't worry about it - go ahead with the changes - its just issue templates, nothing to have an argument about ;)

**Pull request merged**
