### PR TITLE
Redame: Mark shell examples as code

### PR DESCRIPTION
**Pull request by mk-pmb**

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
closing this cuz of inactivity ;) 2014...

**Comment by mk-pmb** [comment]
#Bürgerbeteiligung

**Comment by ulfgebhardt** [comment]
You want it merged @mk-pmb ? if you rebase and reopen the PR I will <3

**Comment by mk-pmb** [comment]
Mostly I found the fate of this PR ironically similar to parts of our political process. :-)
Seems like Github misinterpreted my force-push. I'll open a new PR with a non-master branch name.

**Pull request closed without merging**
